import inspect
import warnings
from io import StringIO

import numpy

try:
    from scipy.io import arff

    HAS_ARFF = True
except:
    HAS_ARFF = False

from sklearn.utils.estimator_checks import _NotAnArray as NotAnArray
from sklearn.utils.validation import check_array as sk_check_array
from sklearn.utils.validation import check_X_y as sk_check_X_y

from tslearn.backend import instantiate_backend


__author__ = "Romain Tavenard romain.tavenard[at]univ-rennes2.fr"


def fix_force_all_finite_warning(func):
    """ Make sure to use sklearn >=1.6 ensure_finite_attribute if available
        rather than deprecated force_all_attribute """
    def wrapper(*args, **kwargs):
        if ('force_all_finite' in kwargs and
                inspect.signature(sk_check_array).parameters.get('ensure_all_finite')):
            kwargs['ensure_all_finite'] = kwargs.pop('force_all_finite')
        return func(*args, **kwargs)
    return wrapper


check_array = fix_force_all_finite_warning(sk_check_array)
check_X_y = fix_force_all_finite_warning(sk_check_X_y)


def check_variable_length_input(X):
    """Input validation on a variable length dataset.

    Parameters
    ----------
    X : object
        Input object to check / convert.

    Returns
    -------
        array_converted : object
        The converted and validated array.
    """
    if getattr(X, "shape", None) is None:
        if isinstance(X, NotAnArray):
            X = check_array(X, allow_nd=True, force_all_finite=False)
        else:
            # Check each time series when X can be of variable length before
            # to_time_series_dataset processing
            for ts in X:
                check_array([ts], allow_nd=True, force_all_finite=False)
    else:
        X = check_array(X, allow_nd=True, force_all_finite=False)
    return to_time_series_dataset(X)


def check_dims(X, X_fit_dims=None, extend=True, check_n_features_only=False):
    """Reshapes X to a 3-dimensional array of X.shape[0] univariate
    timeseries of length X.shape[1] if X is 2-dimensional and extend
    is True. Then checks whether the provided X_fit_dims and the
    dimensions of X (except for the first one), match.

    Parameters
    ----------
    X : array-like
        The first array to be compared.
    X_fit_dims : tuple (default: None)
        The dimensions of the data generated by fit, to compare with
        the dimensions of the provided array X.
        If None, then only perform reshaping of X, if necessary.
    extend : boolean (default: True)
        Whether to reshape X, if it is 2-dimensional.
    check_n_features_only: boolean (default: False)

    Returns
    -------
    array
        Reshaped X array

    Examples
    --------
    >>> X = numpy.empty((10, 3))
    >>> check_dims(X).shape
    (10, 3, 1)
    >>> X = numpy.empty((10, 3, 1))
    >>> check_dims(X).shape
    (10, 3, 1)
    >>> X_fit_dims = (5, 3, 1)
    >>> check_dims(X, X_fit_dims).shape
    (10, 3, 1)
    >>> X_fit_dims = (5, 3, 2)
    >>> check_dims(X, X_fit_dims)  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
    ValueError: Dimensions (except first) must match! ((5, 3, 2) and (10, 3, 1)
    are passed shapes)
    >>> X_fit_dims = (5, 5, 1)
    >>> check_dims(X, X_fit_dims, check_n_features_only=True).shape
    (10, 3, 1)
    >>> X_fit_dims = (5, 5, 2)
    >>> check_dims(
    ...     X,
    ...     X_fit_dims,
    ...     check_n_features_only=True
    ... )  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
    ValueError: Number of features of the provided timeseries must match!
    (last dimension) must match the one of the fitted data!
    ((5, 5, 2) and (10, 3, 1) are passed shapes)

    Raises
    ------
    ValueError
        Will raise exception if X is None or (if X_fit_dims is provided) one
        of the dimensions of the provided data, except the first, does not
        match X_fit_dims.
    """
    if X is None:
        raise ValueError("X is equal to None!")

    if extend and len(X.shape) == 2:
        warnings.warn(
            "2-Dimensional data passed. Assuming these are "
            "{} 1-dimensional timeseries".format(X.shape[0])
        )
        X = X.reshape((X.shape) + (1,))

    if X_fit_dims is not None:
        if check_n_features_only:
            if X_fit_dims[2] != X.shape[2]:
                raise ValueError(
                    "Number of features of the provided timeseries"
                    "(last dimension) must match the one of the fitted data!"
                    " ({} and {} are passed shapes)".format(X_fit_dims, X.shape)
                )
        else:
            if X_fit_dims[1:] != X.shape[1:]:
                raise ValueError(
                    "Dimensions of the provided timeseries"
                    "(except first) must match those of the fitted data!"
                    " ({} and {} are passed shapes)".format(X_fit_dims, X.shape)
                )

    return X


def to_time_series(ts, remove_nans=False, be=None, dtype=float):
    """Transforms a time series so that it fits the format used in ``tslearn``
    models.

    Parameters
    ----------
    ts : array-like, shape=(sz, d) or (sz,)
        The time series to be transformed.
        If shape is (sz,), the time series is assumed to be univariate.
    remove_nans : bool (default: False)
        Whether trailing NaNs at the end of the time series should be removed
        or not
    be : Backend object or string or None
        Backend. If `be` is an instance of the class `NumPyBackend` or the string `"numpy"`,
        the NumPy backend is used.
        If `be` is an instance of the class `PyTorchBackend` or the string `"pytorch"`,
        the PyTorch backend is used.
        If `be` is `None`, the backend is determined by the input arrays.
        See our :ref:`dedicated user-guide page <backend>` for more information.
    dtype : data type (default: float)
        Data type for the returned dataset, depending on the backend.

    Returns
    -------
    ts_out : array-like, shape=(sz, d)
        The transformed time series. This is always guaraneteed to be a new
        time series and never just a view into the old one.

    Examples
    --------
    >>> to_time_series([1, 2])
    array([[1.],
           [2.]])
    >>> to_time_series([1, 2, numpy.nan])
    array([[ 1.],
           [ 2.],
           [nan]])
    >>> to_time_series([1, 2, numpy.nan], remove_nans=True)
    array([[1.],
           [2.]])

    See Also
    --------
    to_time_series_dataset : Transforms a dataset of time series
    """
    be = instantiate_backend(be, ts)
    ts_out = be.array(ts, dtype=dtype)
    return _to_time_series(ts_out, remove_nans, be)


def _to_time_series(ts, remove_nans=False, backend=None):
    """Times series formatting for inputs already converted to a backend."""
    if backend is None:
        backend = instantiate_backend(ts)
    if ts.ndim <= 1:
        ts = ts.reshape(-1, 1)
    if remove_nans:
        ts = ts[:_ts_size(ts, backend=backend)]
    return ts


def to_time_series_dataset(dataset, dtype=float, be=None):
    """Transforms a time series dataset so that it fits the format used in
    ``tslearn`` models.

    Parameters
    ----------
    dataset : array-like, shape=(n_ts, sz, d) or (n_ts, sz) or (sz,)
        The dataset of time series to be transformed. A single time series will
        be automatically wrapped into a dataset with a single entry.
    dtype : data type (default: float)
        Data type for the returned dataset, depending on the backend.
    be : Backend object or string or None
        Backend. If `be` is an instance of the class `NumPyBackend` or the string `"numpy"`,
        the NumPy backend is used.
        If `be` is an instance of the class `PyTorchBackend` or the string `"pytorch"`,
        the PyTorch backend is used.
        If `be` is `None`, the backend is determined by the input arrays.
        See our :ref:`dedicated user-guide page <backend>` for more information.

    Returns
    -------
    dataset_out : array-like, shape=(n_ts, sz, d)
        The transformed dataset of time series.

    Examples
    --------
    >>> to_time_series_dataset([[1, 2]])
    array([[[1.],
            [2.]]])
    >>> to_time_series_dataset([1, 2])
    array([[[1.],
            [2.]]])
    >>> to_time_series_dataset([[1, 2], [1, 4, 3]])
    array([[[ 1.],
            [ 2.],
            [nan]],
    <BLANKLINE>
           [[ 1.],
            [ 4.],
            [ 3.]]])
    >>> to_time_series_dataset([]).shape
    (0, 0, 0)

    See Also
    --------
    to_time_series : Transforms a single time series
    """
    be = instantiate_backend(be, dataset)

    try:
        import pandas as pd

        if isinstance(dataset, pd.DataFrame):
            return to_time_series_dataset(be.array(dataset), be=be)
    except ImportError:
        pass
    if isinstance(dataset, NotAnArray):  # Patch to pass sklearn tests
        return to_time_series_dataset(be.array(dataset), be=be)
    if len(dataset) == 0:
        return be.zeros((0, 0, 0))
    if be.ndim(be.array(dataset[0])) == 0:
        dataset = [dataset]
    n_ts = len(dataset)
    max_sz = max(
        [ts_size(ts, be) for ts in dataset]
    )
    d = be.shape(to_time_series(dataset[0], be=be))[1]
    dataset_out = be.full((n_ts, max_sz, d), be.nan, dtype=dtype)
    for i in range(n_ts):
        ts = to_time_series(dataset[i], remove_nans=True, be=be, dtype=dtype)
        dataset_out[i, : ts.shape[0]] = ts
    return dataset_out


def time_series_to_str(ts, fmt="%.18e"):
    """Transforms a time series to its representation as a string (used when
    saving time series to disk).

    Parameters
    ----------
    ts : array-like
        Time series to be represented.
    fmt : string (default: "%.18e")
        Format to be used to write each value (only ASCII characters).

    Returns
    -------
    string
        String representation of the time-series.

    Examples
    --------
    >>> time_series_to_str([1, 2, 3, 4], fmt="%.1f")
    '1.0 2.0 3.0 4.0'
    >>> time_series_to_str([[1, 3], [2, 4]], fmt="%.1f")
    '1.0 2.0|3.0 4.0'

    See Also
    --------
    load_time_series_txt : Load time series from disk
    str_to_time_series : Transform a string into a time series
    """
    ts_ = to_time_series(ts)
    out = StringIO()
    numpy.savetxt(out, ts_.T, fmt=fmt, delimiter=" ", newline="|", encoding="bytes")
    return out.getvalue()[:-1]  # cut away the trailing "|"


timeseries_to_str = time_series_to_str


def str_to_time_series(ts_str):
    """Reads a time series from its string representation (used when loading
    time series from disk).

    Parameters
    ----------
    ts_str : string
        String representation of the time-series.

    Returns
    -------
    numpy.ndarray
        Represented time-series.

    Examples
    --------
    >>> str_to_time_series("1 2 3 4")
    array([[1.],
           [2.],
           [3.],
           [4.]])
    >>> str_to_time_series("1 2|3 4")
    array([[1., 3.],
           [2., 4.]])

    See Also
    --------
    load_time_series_txt : Load time series from disk
    time_series_to_str : Transform a time series into a string
    """
    dimensions = ts_str.split("|")
    ts = [numpy.fromstring(dim_str, sep=" ") for dim_str in dimensions]
    return to_time_series(numpy.transpose(ts))


str_to_timeseries = str_to_time_series


def save_time_series_txt(fname, dataset, fmt="%.18e"):
    """Writes a time series dataset to disk.

    Parameters
    ----------
    fname : string
        Path to the file in which time series should be written.
    dataset : array-like
        The dataset of time series to be saved.
    fmt : string (default: "%.18e")
        Format to be used to write each value.

    Examples
    --------
    >>> dataset = to_time_series_dataset([[1, 2, 3, 4], [1, 2, 3]])
    >>> save_time_series_txt("tmp-tslearn-test.txt", dataset)

    See Also
    --------
    load_time_series_txt : Load time series from disk
    """
    with open(fname, "w") as f:
        for ts in dataset:
            f.write(time_series_to_str(ts, fmt=fmt) + "\n")


save_timeseries_txt = save_time_series_txt


def load_time_series_txt(fname):
    """Loads a time series dataset from disk.

    Parameters
    ----------
    fname : string
        Path to the file from which time series should be read.

    Returns
    -------
    numpy.ndarray or array of numpy.ndarray
        The dataset of time series.

    Examples
    --------
    >>> dataset = to_time_series_dataset([[1, 2, 3, 4], [1, 2, 3]])
    >>> save_time_series_txt("tmp-tslearn-test.txt", dataset)
    >>> reloaded_dataset = load_time_series_txt("tmp-tslearn-test.txt")

    See Also
    --------
    save_time_series_txt : Save time series to disk
    """
    with open(fname, "r") as f:
        return to_time_series_dataset(
            [str_to_time_series(row) for row in f.readlines()]
        )


load_timeseries_txt = load_time_series_txt


def check_equal_size(dataset, be=None):
    """Check if all time series in the dataset have the same size.

    Parameters
    ----------
    dataset: array-like
        The dataset to check.

    Returns
    -------
    bool
        Whether all time series in the dataset have the same size.

    Examples
    --------
    >>> check_equal_size([[1, 2, 3], [4, 5, 6], [5, 3, 2]])
    True
    >>> check_equal_size([[1, 2, 3, 4], [4, 5, 6], [5, 3, 2]])
    False
    >>> check_equal_size([])
    True
    """
    be = instantiate_backend(be, dataset)

    dataset_ = to_time_series_dataset(dataset, be=be)
    return _check_equal_size(dataset_, backend=be)


def _check_equal_size(dataset, backend=None):
    """Check equal size for already formatted dataset."""
    if backend is None:
        backend = instantiate_backend(dataset)
    if len(dataset) == 0:
        return True

    size = _ts_size(dataset[0], backend=backend)
    return all(_ts_size(ds) == size for ds in dataset[1:])



def ts_size(ts, be=None):
    """Returns actual time series size.

    Final timesteps that have `NaN` values for all dimensions will be removed
    from the count. Infinity and negative infinity ar considered valid time
    series values.

    Parameters
    ----------
    ts : array-like
        A time series.
    be : Backend object or string or None
        Backend. If `be` is an instance of the class `NumPyBackend` or the string `"numpy"`,
        the NumPy backend is used.
        If `be` is an instance of the class `PyTorchBackend` or the string `"pytorch"`,
        the PyTorch backend is used.
        If `be` is `None`, the backend is determined by the input arrays.
        See our :ref:`dedicated user-guide page <backend>` for more information.

    Returns
    -------
    int
        Actual size of the time series.

    Examples
    --------
    >>> ts_size([1, 2, 3, numpy.nan])
    3
    >>> ts_size([1, numpy.nan])
    1
    >>> ts_size([numpy.nan])
    0
    >>> ts_size([[1, 2],
    ...          [2, 3],
    ...          [3, 4],
    ...          [numpy.nan, 2],
    ...          [numpy.nan, numpy.nan]])
    4
    >>> ts_size([numpy.nan, 3, numpy.inf, numpy.nan])
    3
    """
    be = instantiate_backend(be, ts)
    ts_ = to_time_series(ts, be=be)
    return _ts_size(ts_, backend=be)


def _ts_size(ts, backend=None):
    """Ts size computation for already formatted time series."""
    if backend is None:
        backend = instantiate_backend(ts)
    sz = len(ts)
    while sz > 0 and backend.all(backend.isnan(ts[sz - 1])):
        sz -= 1
    return sz


def to_timestamps(ts_timestamps, remove_nans=False):
    """Transforms a timestamp sequence into the format used in tslearn.

    Parameters
    ----------
    ts_timestamps : array-like, shape=(sz,)
        Timestamps for a single time series. Must be strictly monotonically
        increasing (ignoring trailing NaNs).
    remove_nans : bool (default: False)
        Whether trailing NaN values should be removed.

    Returns
    -------
    numpy.ndarray, shape=(sz,)
        Float64 1-D timestamp array.

    Raises
    ------
    ValueError
        If the non-NaN timestamps are not strictly monotonically increasing.

    Examples
    --------
    >>> to_timestamps([0., 1., 2.])
    array([0., 1., 2.])
    >>> to_timestamps([0., 1., numpy.nan])
    array([ 0.,  1., nan])
    >>> to_timestamps([0., 1., numpy.nan], remove_nans=True)
    array([0., 1.])

    See Also
    --------
    to_timestamps_dataset : Transforms a dataset of timestamp sequences
    """
    ts = numpy.array(ts_timestamps, dtype=float).ravel()
    valid = ts[~numpy.isnan(ts)]
    if len(valid) > 1 and not numpy.all(numpy.diff(valid) > 0):
        raise ValueError(
            "Timestamps must be strictly monotonically increasing. "
            "Got: {}".format(valid)
        )
    if remove_nans:
        sz = len(ts)
        while sz > 0 and numpy.isnan(ts[sz - 1]):
            sz -= 1
        ts = ts[:sz]
    return ts


def to_timestamps_dataset(timestamps_list, max_sz=None):
    """Transforms a list of timestamp sequences into a padded dataset.

    Shorter sequences are padded with NaN to match the longest one (or
    ``max_sz`` if provided), mirroring the behaviour of
    :func:`to_time_series_dataset`.

    Parameters
    ----------
    timestamps_list : list of array-like or array-like, shape=(n_ts, sz) or None
        List of 1-D timestamp arrays of possibly varying lengths.
        If already a 2-D uniform array, it is returned as-is (after dtype
        conversion). If None, returns None.
    max_sz : int or None (default: None)
        Pad all sequences to this length. If None, uses the length of the
        longest sequence.

    Returns
    -------
    numpy.ndarray, shape=(n_ts, max_sz) or None
        NaN-padded timestamp dataset, or None if input is None.

    Examples
    --------
    >>> to_timestamps_dataset([[0., 1., 2.], [0., 2.]])
    array([[ 0.,  1.,  2.],
           [ 0.,  2., nan]])
    >>> to_timestamps_dataset(None) is None
    True

    See Also
    --------
    to_timestamps : Transforms a single timestamp sequence
    """
    if timestamps_list is None:
        return None
    # Fast path: already a uniform 2-D array
    try:
        arr = numpy.array(timestamps_list, dtype=float)
        if arr.ndim == 2:
            return arr
    except (ValueError, TypeError):
        pass
    # Variable-length path
    n = len(timestamps_list)
    if n == 0:
        return numpy.zeros((0, 0))
    converted = [to_timestamps(t) for t in timestamps_list]
    m = max_sz if max_sz is not None else max(len(t) for t in converted)
    out = numpy.full((n, m), numpy.nan)
    for i, t in enumerate(converted):
        out[i, : len(t)] = t
    return out


def check_timestamps_dataset(timestamps, X):
    """Validate a timestamp dataset against a time series dataset X.

    Checks that ``timestamps`` has shape ``(n_ts, max_sz)`` matching ``X``,
    that its NaN positions are consistent with ``X``, and that each row is
    strictly monotonically increasing (ignoring trailing NaNs).

    Parameters
    ----------
    timestamps : array-like, shape=(n_ts, max_sz)
        Timestamp dataset to validate.
    X : array-like, shape=(n_ts, max_sz, d)
        Time series dataset to match against.

    Returns
    -------
    numpy.ndarray, shape=(n_ts, max_sz)
        Validated timestamps array.

    Raises
    ------
    ValueError
        If the shape does not match or timestamps are not monotonically
        increasing.

    Examples
    --------
    >>> import numpy as np
    >>> X = numpy.array([[[1.], [2.], [3.]], [[4.], [5.], [numpy.nan]]])
    >>> t = numpy.array([[0., 1., 2.], [0., 1., numpy.nan]])
    >>> result = check_timestamps_dataset(t, X)
    >>> result.shape
    (2, 3)
    """
    timestamps = numpy.array(timestamps, dtype=float)
    if timestamps.ndim == 1:
        timestamps = timestamps.reshape(1, -1)
    n_ts, max_sz, d = X.shape
    if timestamps.shape != (n_ts, max_sz):
        raise ValueError(
            "timestamps shape {} does not match X shape {}. "
            "Expected ({}, {}).".format(timestamps.shape, X.shape, n_ts, max_sz)
        )
    for i in range(n_ts):
        t_i = timestamps[i]
        valid = t_i[~numpy.isnan(t_i)]
        if len(valid) > 1 and not numpy.all(numpy.diff(valid) > 0):
            raise ValueError(
                "Timestamps for series {} are not strictly monotonically "
                "increasing.".format(i)
            )
    return timestamps


def ts_zeros(sz, d=1):
    """Returns a time series made of zero values.

    Parameters
    ----------
    sz : int
        Time series size.
    d : int (optional, default: 1)
        Time series dimensionality.

    Returns
    -------
    numpy.ndarray
        A time series made of zeros.

    Examples
    --------
    >>> ts_zeros(3, 2)  # doctest: +NORMALIZE_WHITESPACE
    array([[0., 0.],
           [0., 0.],
           [0., 0.]])
    >>> ts_zeros(5).shape
    (5, 1)
    """
    return numpy.zeros((sz, d))


def check_dataset(
    X, force_univariate=False, force_equal_length=False, force_single_time_series=False
):
    """Check if X is a valid tslearn dataset, with possibly additional extra
    constraints.

    Parameters
    ----------
    X: array-like, shape=(n_ts, sz, d)
        Time series dataset.
    force_univariate: bool (default: False)
        If True, only univariate datasets are considered valid.
    force_equal_length: bool (default: False)
        If True, only equal-length datasets are considered valid.
    force_single_time_series: bool (default: False)
        If True, only datasets made of a single time series are considered
        valid.

    Returns
    -------
    array-like, shape=(n_ts, sz, d)
        Formatted dataset, if it is valid

    Raises
    ------
    ValueError
        Raised if X is not a valid dataset, or one of the constraints is not
        satisfied.

    Examples
    --------
    >>> X = [[1, 2, 3], [1, 2, 3, 4]]
    >>> X_new = check_dataset(X)
    >>> X_new.shape
    (2, 4, 1)
    >>> check_dataset(
    ...     X,
    ...     force_equal_length=True
    ... )  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
    ...
    ValueError: All the time series in the array should be of equal lengths.
    >>> other_X = numpy.random.randn(3, 10, 2)
    >>> check_dataset(
    ...     other_X,
    ...     force_univariate=True
    ... )  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
    ...
    ValueError: Array should be univariate and is of shape: (3, 10, 2)
    >>> other_X = numpy.random.randn(3, 10, 2)
    >>> check_dataset(
    ...     other_X,
    ...     force_single_time_series=True
    ... )  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
    ...
    ValueError: Array should be made of a single time series (3 here)
    """
    X_ = to_time_series_dataset(X)
    if force_univariate and X_.shape[2] != 1:
        raise ValueError(
            "Array should be univariate and is of shape: {}".format(X_.shape)
        )
    if force_equal_length and not _check_equal_size(X_):
        raise ValueError(
            "All the time series in the array should be of equal lengths"
        )
    if force_single_time_series and X_.shape[0] != 1:
        raise ValueError(
            "Array should be made of a single time series "
            "({} here)".format(X_.shape[0])
        )
    return X_


def _load_arff_uea(dataset_path):
    """Load arff file for uni/multi variate dataset

    Parameters
    ----------
    dataset_path: string of dataset_path
        Path to the ARFF file to be read

    Returns
    -------
    x: numpy array of shape (n_timeseries, n_timestamps, n_features)
        Time series dataset
    y: numpy array of shape (n_timeseries, )
        Vector of targets

    Raises
    ------
    ImportError: if the version of *Scipy* is too old (pre 1.3.0)
    Exception: on any failure, e.g. if the given file does not exist or is
               corrupted
    """
    if not HAS_ARFF:
        raise ImportError(
            "scipy 1.3.0 or newer is required to load "
            "time series datasets from arff format."
        )
    data, meta = arff.loadarff(dataset_path)
    names = meta.names()  # ["input", "class"] for multi-variate

    # firstly get y_train
    y_ = data[names[-1]]  # data["class"]
    y = numpy.array(y_).astype("str")

    # get x_train
    if len(names) == 2:  # len=2 => multi-variate
        x_ = data[names[0]]
        x_ = numpy.asarray(x_.tolist())

        nb_example = x_.shape[0]
        nb_channel = x_.shape[1]
        length_one_channel = len(x_.dtype.descr)
        x = numpy.empty([nb_example, length_one_channel, nb_channel])

        for i in range(length_one_channel):
            # x_.dtype.descr: [('t1', '<f8'), ('t2', '<f8'), ('t3', '<f8')]
            time_stamp = x_.dtype.descr[i][0]  # ["t1", "t2", "t3"]
            x[:, i, :] = x_[time_stamp]

    else:  # uni-variate situation
        x_ = data[names[:-1]]
        x = numpy.asarray(x_.tolist(), dtype=float)
        x = x.reshape(len(x), -1, 1)

    return x, y


def _load_txt_uea(dataset_path):
    """Load arff file for uni/multi variate dataset

    Parameters
    ----------
    dataset_path: string of dataset_path
        Path to the TXT file to be read

    Returns
    -------
    x: numpy array of shape (n_timeseries, n_timestamps, n_features)
        Time series dataset
    y: numpy array of shape (n_timeseries, )
        Vector of targets

    Raises
    ------
    Exception: on any failure, e.g. if the given file does not exist or is
               corrupted
    """
    data = numpy.loadtxt(dataset_path)
    X = to_time_series_dataset(data[:, 1:])
    y = data[:, 0].astype(int)
    return X, y
